### ISSUE TITLE
Missing libpdal_base.so after install

### ISSUE THREAD

**Issue by Karl-Keller** [conda-forge/python-pdal-feedstock#77]
Hopefully, I'm in the right pdal feedstock.  Brought this up in pdal community email as well.

Working in Ubuntu 20.04, Python 3.8
Loading pdal with 'conda install -c conda-forge python-pdal pdal gdal
Running a test with python -m pdal
During from pdal import libpdalpython, I get:
ImportError: libpdal_base.so.13: cannot open shared object file: No such file or directory.

On inspection of the pdal site-package, I see it's linked libpdal_base.so.12.

I've also run this with 'conda install -c conda-forge python-pdal' only in a new environment.  Same result.

**Comment by Karl-Keller** [comment]
I see libpdal_base13 built in Ubuntu 22.04 - is the Linux upgrade required for Ubuntu?  If so, why is the install on 20.04 looking for 13?

**Comment by hobu** [comment]
Can you please try now post-2.5.0 release?

**Comment by Karl-Keller** [comment]
Installed the latest using 'conda install -c conda-forge python-pdal pdal gdal'.  Installed fine and is now showing pdal = 2.5.0, python-pdal = 3.2.2, gdal=3.6.2. 

 'import pdal' works fine now.
